# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1657ee05dbc4d4b0e466301e82536eaea5b303cc81139575bdbd939845c5f25a4179e7bdf855e65c38ea8c25d22481631bca9bce7fbf610672a82f113f21a16c

test:
  secret_key_base: 58d89ac2d1d9047636a8462239b460450b587ef455bffe0ec947b039c96446380344d55bf1a85d93cd1f733885685459cdaa630ecb31a15e6a4a17261c999100

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
